### ISSUE TITLE
CZML does not appear to support /P style ISO-8601 interval duration specification

### ISSUE THREAD

**Issue by hcarter333** [AnalyticalGraphicsInc/czml-writer#197]
When an interval is specified in a CZML file as 

`"interval": "2024-03-14T23:25:00Z/P0Y0M0DT0H1M",`

The sandcastle app console returns the following errors stack:
```
DeveloperError: Invalid ISO 8601 date.
Error
    at new DeveloperError (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:10552:13)
    at JulianDate.fromIso8601 (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:19794:21)
    at TimeInterval.fromIso8601 (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:41690:38)
    at intervalFromString (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:140320:33)
    at processProperty (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:140338:28)
    at processPacketData (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:140477:9)
    at Array.processPolyline (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:143368:5)
    at processCzmlPacket (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:143936:28)
    at CzmlDataSource._processCzml (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:144258:9)
    at loadCzml (https://sandcastle.cesium.com/CesiumUnminified/Cesium.js:144049:20)

```
Per the Wikipedia page, interval [durations](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals) can be specified using the /P format.

There's an example of this issue [here](https://sandcastle.cesium.com/#c=bVRrb5swFP0rFp8yiTiGvFlaTaJVV5Uo0cImtaWqHPASq8ZGtkmUTv3vs0NDSBOEwByfc1++l1RwpUH6njNwBZ4TDsA/+wCAZgFInEykZU64Thy3gjnOid0In6YRuCMiJ1pSogIwF2zHKCc1c0OkooJbsgdRDadMpG/BwYvxwzWRG8wsz0d+r426ba8X+93A7wUIPXW+gEML1taMvVJKE2BMq7gumWiw85JpWjBKZAAGqIYl5qu9PJrN5q+LeDZvaJQmhd1bPC7i2+lrGM3Ch9fp7yi+n0f3t79q5sf+XT1PivgwjsKzAp6AxWfxGnUphKLa1E81MJMtllqsJC7WNL0hK0ls6Z/bHhrAfn8w9nxvgPyB73tu14fdodcdot7Q8/xxz++5yAXt0QiO+6Ou2/OhP0QjF73UeX4cq4TNmVB7Jg3XSjCahYIJeQKbmC5gpqSrJTah+f2+C9D+Nsujs1OHzfVxlThqLbaJE1SNebi+OLK8QxNZ7lkP9PdtNEePaIpuYvTTmzYO92hjKQQjmFsTWpbkcqDHBA7vLc30OgD9Y0MynBexuJOi5Fll66xBXr4nPN1P3oaSLZFm9jjZgpAoWubwzx5rJU66/w4F19g0h0ycb7UuwxovRClTMpcip4oYE5/y0AzzTb0NmcBZyw64FVfu4FGtIM6y1pm1BvddiDwWlykJd1xnovSOketD/j9oXgipQSlZC8KOJnnBTD+pzrJM34iGqVJWaqmTTlM6yejGTMzVhbxtUZUyO39Lxhb03fxlricdwz+T2mwpX83M34fhnaWtveuoAiGEk475vKzU5vyXWDYsV4z/).

**Comment by hcarter333** [comment]
The issue appears to be in the following [code](https://sandcastle.cesium.com/CesiumUnminified/Cesium.js) 

![image](https://github.com/AnalyticalGraphicsInc/czml-writer/assets/363004/46afafbb-c596-479a-ae22-4c5cca9c90e5)

Notice that there is not context in the call that assigns `stop2`. It has no way to handle 'P' specifiers.

**Comment by shunter** [comment]
Do you have an example of czml-writer code that generates CZML output with the duration syntax?
